package dto

const (
	ProjectNameMaxLength        = 128
	ProjectRepoURLMaxLength     = 512
	ProjectDescriptionMaxLength = 4000
	ProjectStackMaxLength       = 256
	ProjectDatabaseMaxLength    = 128
	ProjectCodingRulesMaxLength = 12000
)

// ProjectCreateDTO is the input for creating a project.
type ProjectCreateDTO struct {
	Name          string `json:"name" binding:"required"`
	Description   string `json:"description"`
	RepoURL       string `json:"repo_url"`
	FrontendStack string `json:"frontend_stack"`
	BackendStack  string `json:"backend_stack"`
	Database      string `json:"database"`
	UIStyle       string `json:"ui_style"`
	CodingRules   string `json:"coding_rules"`
}

// ProjectUpdateDTO is the input for updating a project. All fields optional.
type ProjectUpdateDTO struct {
	Name          *string `json:"name"`
	Description   *string `json:"description"`
	RepoURL       *string `json:"repo_url"`
	FrontendStack *string `json:"frontend_stack"`
	BackendStack  *string `json:"backend_stack"`
	Database      *string `json:"database"`
	UIStyle       *string `json:"ui_style"`
	CodingRules   *string `json:"coding_rules"`
}

// ProjectDTO is the full project response.
type ProjectDTO struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	RepoURL       string `json:"repo_url"`
	FrontendStack string `json:"frontend_stack"`
	BackendStack  string `json:"backend_stack"`
	Database      string `json:"database"`
	UIStyle       string `json:"ui_style"`
	CodingRules   string `json:"coding_rules"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

// ProjectSummaryDTO is a lightweight project for list views.
type ProjectSummaryDTO struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	RepoURL      string   `json:"repo_url"`
	ReportCount  int64    `json:"report_count"`
	AverageScore *float64 `json:"average_score"`
	CreatedAt    string   `json:"created_at"`
	UpdatedAt    string   `json:"updated_at"`
}

// ProjectDeleteDTO describes the impact of deleting a project profile.
// Historical reports remain available and only have their project association cleared.
type ProjectDeleteDTO struct {
	DetachedReportCount int64 `json:"detached_report_count"`
}

// ProjectArtifactDTO points to a file generated by the latest successful report
// for a project-capable artifact tool.
type ProjectArtifactDTO struct {
	ToolType    string `json:"tool_type"`
	ReportID    string `json:"report_id"`
	ReportTitle string `json:"report_title"`
	Filename    string `json:"filename"`
	MimeType    string `json:"mime_type"`
	CreatedAt   string `json:"created_at"`
}

// ProjectStatsDTO holds aggregated stats for a project detail view.
type ProjectStatsDTO struct {
	TotalReports      int64                  `json:"total_reports"`
	AverageScore      *float64               `json:"average_score"`
	ToolUsage         map[string]int64       `json:"tool_usage"`
	HighSeverityCount int64                  `json:"high_severity_count"`
	RecentReports     []RecentReportDTO      `json:"recent_reports"`
	QualityTrend      []QualityTrendPointDTO `json:"quality_trend"`
	LatestArtifacts   []ProjectArtifactDTO   `json:"latest_artifacts"`
}

// ListProjectsQuery holds list filters.
type ListProjectsQuery struct {
	Search   string `form:"search"`
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
}

// SetDefaults clamps page/page_size.
func (q *ListProjectsQuery) SetDefaults() {
	if q.Page < 1 {
		q.Page = 1
	}
	if q.PageSize < 1 {
		q.PageSize = 10
	}
	if q.PageSize > 100 {
		q.PageSize = 100
	}
}
